# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'COMP367-Windows'

stages:
- stage: Deliver
  jobs:
  - job: DeliverArtifact
    steps:
    - checkout: self
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'backend-artifacts'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'frontend-artifacts'
        publishLocation: 'Container'
    - script: echo Delivering artifacts...
      displayName: 'Mock Deliver Artifacts Step'

- stage: DeployToDev
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: DeployToDev
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Mock deploying to Development environment...
            displayName: 'Mock Deploy to Dev'

- stage: DeployToQAT
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: DeployToQAT
    environment: 'qat'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Mock deploying to QAT environment...
            displayName: 'Mock Deploy to QAT'

- stage: DeployToStaging
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: DeployToStaging
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Mock deploying to Staging environment...
            displayName: 'Mock Deploy to Staging'

- stage: DeployToProd
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: DeployToProd
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Mock deploying to Production environment...
            displayName: 'Mock Deploy to Prod'
